modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="piper"
version="1.1.2b"
displayName="Piper"
displayURL="https://www.curseforge.com/minecraft/mc-mods/piper"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/Piper/1.19/update.json"
credits="Smileycorp"
authors="bstylia14 for the original mod concept and for providing ideas during development."
description="An optional addon to Follow Me, adds an item to make mobs follow you."

[[dependencies.piper]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.piper]]
    modId="followme"
    mandatory=true
    versionRange="[1.1.6,)"
    ordering="NONE"
    side="BOTH"